
server:
  port: 8090
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动包
    url: jdbc:mysql://47.104.107.189:33306/springcloud_db01?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: yuyue520
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  #视图配置
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8